version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

  backend1:
    build:
      context: ./backend
    container_name: backend-instance-1
    environment:
      - MONGO_URI=mongodb://mongo:27017/livestream
    depends_on:
      - mongo
      - redis

  backend2:
    build:
      context: ./backend
    container_name: backend-instance-2
    environment:
      - MONGO_URI=mongodb://mongo:27017/livestream
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-balancer
    ports:
      - "5050:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
